In [ ]:
import pandas as pd
import numpy as np
import os
os.chdir("..")

from src.utils.data_retrieval import get_stats_table

In [4]:
df = get_stats_table(fully_evolved=True)
df

             name   HP  Attack  Defense  Sp. Attack  Sp. Defense  Speed
0        Venusaur   80      82       83         100          100     80
1       Charizard   78      84       78         109           85    100
2       Blastoise   79      83      100          85          105     78
3      Butterfree   60      45       50          90           80     70
4        Beedrill   65      90       40          45           80     75
..            ...  ...     ...      ...         ...          ...    ...
529   Raging-bolt  125      73       91         137           89     75
530  Iron-boulder   90     120       80          68          108    124
531    Iron-crown   90      72      100         122          108     98
532     Terapagos   90      65       85          65           85     60
533     Pecharunt   88      88      160          88           88     88

[534 rows x 7 columns]

In [8]:
# example filtering
df[df["Speed"] < 60]

             name   HP  Attack  Defense  Sp. Attack  Sp. Defense  Speed
15     Wigglytuff  140      70       45          85           50     45
16      Vileplume   75      80       85         110           90     50
17       Parasect   60      95       80          60           80     30
25        Machamp   90     130       80          65           85     55
28          Golem   80     120      130          55           65     45
..            ...  ...     ...      ...         ...          ...    ...
496     Kingambit  100     135      120          60           85     50
499  Brute-bonnet  111     127       99          79           99     55
505    Iron-hands  154     140      108          50           68     50
513       Ting-lu  155     110      125          55           80     45
527     Hydrapple  106      80      110         120           80     44

[137 rows x 7 columns]

In [ ]:
# multiple filters
df[df["Speed"] < 60][df["Sp. Attack"] > 110]

C:\Users\zmine\AppData\Local\Temp\ipykernel_24468\2953367735.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[df["Speed"] < 60][df["Sp. Attack"] > 110]

          name   HP  Attack  Defense  Sp. Attack  Sp. Defense  Speed
39   Exeggutor   95      95       85         125           75     55
56     Omastar   70      60      125         115           70     55
76    Ampharos   90      75       85         115           90     55
150   Cacturne   70     115       60         115           60     55
171   Gorebyss   55      84      105         114           75     52
286  Reuniclus  110      65       75         125           85     30
298   Beheeyem   75      75       75         125           95     40
337  Clawitzer   71      73       88         120           89     59
360   Vikavolt   77      70       90         145           75     43
382     Drampa   78      60       85         135           91     36
427  Hatterene   57      90       95         136          103     29
431    Cursola   60      95       50         145          130     30
467   Arboliva   78      69       90         125          109     39
479     Rabsca   75      50       85         115          100     45
527  Hydrapple  106      80      110         120           80     44

In [15]:
df.sort_values("HP", ascending=False)

          name   HP  Attack  Defense  Sp. Attack  Sp. Defense  Speed
106    Blissey  255      10       10          75          135     55
397   Guzzlord  223     101       53          97           53     43
451  Regidrago  200     100       50         100           50     80
88   Wobbuffet  190      33       58          33           58     33
144    Wailord  170      90       45          90           45     60
..         ...  ...     ...      ...         ...          ...    ...
173    Luvdisc   43      30       55          40           65     97
482    Wugtrio   35     100       50          50           70    120
19     Dugtrio   35     100       50          50           70    120
93     Shuckle   20      10      230          10          230      5
129   Shedinja    1      90       45          30           30     40

[534 rows x 7 columns]